
services:
  sandbox:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspaces/ocl-sandbox
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${JUPYTER_NB_PORT}:8888"  # Jupyter
    command: sleep infinity  # Deixa o container rodando até você abrir o DevContainer sobre ele
    networks:
      - devnet

  icdapi:
    image: whoicd/icd-api
    environment:
      - acceptLicense=true
      - saveAnalytics=true
    networks:
      - devnet

  db-sandbox:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --local-infile=1
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - devnet
      - cloudbeaver

networks:
  devnet:
    driver: bridge
  cloudbeaver:
    name: cloudbeaver
    external: true